export const adminStats = [
  { label: "Total Users", value: "24,892", detail: "128 new accounts today" },
  { label: "Total Jobs", value: "18,706", detail: "1,204 currently open" },
  { label: "Total Applications", value: "96,341", detail: "4,812 pending review" },
];

export const users = [
  {
    name: "John Smith",
    email: "john.smith@email.com",
    location: "San Francisco, CA",
    role: "Software Engineer",
    applied: 15,
    accepted: 0,
    rejected: 5,
    resumeScore: 89,
    avatarColor: "bg-blue-600",
    status: "Active",
    joined: "Jul 02, 2026",
  },
  {
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    location: "New York, NY",
    role: "Data Scientist",
    applied: 10,
    accepted: 0,
    rejected: 2,
    resumeScore: 92,
    avatarColor: "bg-violet-600",
    status: "Active",
    joined: "Jul 01, 2026",
  },
  {
    name: "Michael Chen",
    email: "m.chen@email.com",
    location: "Seattle, WA",
    role: "Backend Developer",
    applied: 17,
    accepted: 1,
    rejected: 3,
    resumeScore: 78,
    avatarColor: "bg-emerald-500",
    status: "Active",
    joined: "Jun 29, 2026",
  },
  {
    name: "Emily Davis",
    email: "emily.d@email.com",
    location: "Austin, TX",
    role: "UX Designer",
    applied: 12,
    accepted: 0,
    rejected: 4,
    resumeScore: 85,
    avatarColor: "bg-amber-500",
    status: "Active",
    joined: "Jun 28, 2026",
  },
  {
    name: "Alex Turner",
    email: "a.turner@email.com",
    location: "Boston, MA",
    role: "Full Stack Dev",
    applied: 19,
    accepted: 0,
    rejected: 6,
    resumeScore: 71,
    avatarColor: "bg-red-500",
    status: "Active",
    joined: "Jun 27, 2026",
  },
  {
    name: "Priya Patel",
    email: "p.patel@email.com",
    location: "San Jose, CA",
    role: "ML Engineer",
    applied: 14,
    accepted: 1,
    rejected: 2,
    resumeScore: 94,
    avatarColor: "bg-sky-600",
    status: "Active",
    joined: "Jun 26, 2026",
  },
  {
    name: "James Wilson",
    email: "j.wilson@email.com",
    location: "Denver, CO",
    role: "DevOps Engineer",
    applied: 9,
    accepted: 0,
    rejected: 1,
    resumeScore: 83,
    avatarColor: "bg-orange-500",
    status: "Active",
    joined: "Jun 25, 2026",
  },
  {
    name: "Aisha Brown",
    email: "a.brown@email.com",
    location: "Chicago, IL",
    role: "Product Manager",
    applied: 16,
    accepted: 0,
    rejected: 5,
    resumeScore: 76,
    avatarColor: "bg-pink-500",
    status: "Active",
    joined: "Jun 24, 2026",
  },
  {
    name: "Ryan Lee",
    email: "r.lee@email.com",
    location: "Dallas, TX",
    role: "Cloud Architect",
    applied: 11,
    accepted: 1,
    rejected: 2,
    resumeScore: 88,
    avatarColor: "bg-cyan-500",
    status: "Active",
    joined: "Jun 23, 2026",
  },
  {
    name: "Nina Patel",
    email: "nina.p@email.com",
    location: "Atlanta, GA",
    role: "Data Engineer",
    applied: 18,
    accepted: 0,
    rejected: 4,
    resumeScore: 81,
    avatarColor: "bg-purple-500",
    status: "Active",
    joined: "Jun 22, 2026",
  },
];

export const jobs = [
  {
    title: "Senior Frontend Engineer",
    company: "BluePeak Labs",
    logo: "BL",
    location: "Remote",
    salary: "$135K - $165K",
    type: "Full-time",
    applicants: 214,
    posted: "Jul 06, 2026",
    status: "Open",
  },
  {
    title: "Product Designer",
    company: "Northstar AI",
    logo: "NA",
    location: "New York, NY",
    salary: "$110K - $140K",
    type: "Full-time",
    applicants: 156,
    posted: "Jul 05, 2026",
    status: "Open",
  },
  {
    title: "Data Analyst",
    company: "CloudHive",
    logo: "CH",
    location: "Austin, TX",
    salary: "$82K - $105K",
    type: "Hybrid",
    applicants: 214,
    posted: "Jul 02, 2026",
    status: "Closed",
  },
  {
    title: "Talent Operations Lead",
    company: "HireOS",
    logo: "HO",
    location: "San Francisco, CA",
    salary: "$120K - $150K",
    type: "Full-time",
    applicants: 98,
    posted: "Jul 01, 2026",
    status: "Open",
  },
];

export const resumes = [
  {
    candidate: "Maya Chen",
    email: "maya.chen@email.com",
    uploaded: "Jul 06, 2026",
    updated: "Jul 08, 2026",
    score: "94",
    role: "Product Manager",
    status: "Reviewed",
  },
  {
    candidate: "Aarav Sharma",
    email: "aarav.sharma@email.com",
    uploaded: "Jul 06, 2026",
    updated: "Jul 07, 2026",
    score: "88",
    role: "Backend Engineer",
    status: "Reviewed",
  },
  {
    candidate: "Sofia Reed",
    email: "sofia.reed@email.com",
    uploaded: "Jul 05, 2026",
    updated: "Jul 06, 2026",
    score: "76",
    role: "UX Researcher",
    status: "Needs Revision",
  },
  {
    candidate: "Noah Kim",
    email: "noah.kim@email.com",
    uploaded: "Jul 05, 2026",
    updated: "Jul 08, 2026",
    score: "91",
    role: "Data Scientist",
    status: "Reviewed",
  },
  {
    candidate: "Elena Cruz",
    email: "elena.cruz@email.com",
    uploaded: "Jul 04, 2026",
    updated: "Jul 04, 2026",
    score: "69",
    role: "Marketing Analyst",
    status: "Pending",
  },
];

export const applications = [
  {
    applicant: "Maya Chen",
    email: "maya.chen@email.com",
    job: "Product Manager",
    company: "Northstar AI",
    location: "New York, NY",
    date: "Jul 06, 2026",
    status: "Accepted",
  },
  {
    applicant: "Aarav Sharma",
    email: "aarav.sharma@email.com",
    job: "Backend Engineer",
    company: "BluePeak Labs",
    location: "Remote",
    date: "Jul 05, 2026",
    status: "Pending",
  },
  {
    applicant: "Sofia Reed",
    email: "sofia.reed@email.com",
    job: "UX Researcher",
    company: "CloudHive",
    location: "Austin, TX",
    date: "Jul 04, 2026",
    status: "In Review",
  },
  {
    applicant: "Noah Kim",
    email: "noah.kim@email.com",
    job: "Data Scientist",
    company: "HireOS",
    location: "San Francisco, CA",
    date: "Jul 03, 2026",
    status: "Rejected",
  },
];

export const companies = [
  {
    name: "BluePeak Labs",
    logo: "BL",
    industry: "AI Infrastructure",
    location: "Remote-first",
    jobs: 24,
  },
  {
    name: "Northstar AI",
    logo: "NA",
    industry: "Enterprise SaaS",
    location: "New York, NY",
    jobs: 18,
  },
  {
    name: "CloudHive",
    logo: "CH",
    industry: "Cloud Analytics",
    location: "Austin, TX",
    jobs: 11,
  },
  {
    name: "HireOS",
    logo: "HO",
    industry: "HR Technology",
    location: "San Francisco, CA",
    jobs: 31,
  },
];

export const recentJobPosts = [
  "BluePeak Labs posted Senior Frontend Engineer.",
  "HireOS posted Talent Operations Lead.",
  "Northstar AI posted Product Designer.",
  "CloudHive posted Data Analyst.",
  "BrightPath Health posted UX Researcher.",
];

export const recentApplications = [
  "Maya Chen applied for Product Manager at Northstar AI.",
  "Sofia Reed applied for UX Researcher at CloudHive.",
  "Aarav Sharma applied for Backend Engineer at BluePeak Labs.",
  "Noah Kim applied for Data Scientist at HireOS.",
  "Elena Vargas applied for Talent Operations Lead at HireOS.",
];

export const recentSignups = [
  "Rahul Mehta created a new candidate account.",
  "Priya Nair signed up for resume review.",
  "Jordan Lee created a new candidate account.",
  "Maya Chen created a new candidate account.",
  "Noah Kim signed up for job matching.",
];
