const rawSkills = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Dart",
  "Git",
  "Data Structures",
  "Algorithms",
  "Object-Oriented Programming",
  "Problem Solving",
  "Debugging",
  "HTML5",
  "CSS3",
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Redux",
  "Tailwind CSS",
  "Bootstrap",
  "Sass",
  "jQuery",
  "Webpack",
  "Responsive Design",
  "Web Accessibility",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Ruby on Rails",
  "Laravel",
  ".NET",
  "REST APIs",
  "API Integration",
  "GraphQL",
  "Microservices",
  "API Design",
  "Authentication & Authorization",
  "JWT",
  "Role-Based Access Control",
  "Software Testing",
  "SQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Firebase",
  "Database Design",
  "Database Administration",
  "Query Optimization",
  "Flutter",
  "React Native",
  "Android SDK",
  "iOS Development",
  "Mobile UI Design",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "Terraform",
  "Ansible",
  "Linux",
  "Linux Administration",
  "Bash",
  "Nginx",
  "System Design",
  "Site Reliability Engineering",
  "Infrastructure as Code",
  "Monitoring",
  "Manual Testing",
  "Automation Testing",
  "Playwright",
  "Cypress",
  "Selenium",
  "Jest",
  "API Testing",
  "Postman",
  "Test Case Design",
  "Bug Tracking",
  "Quality Assurance",
  "Regression Testing",
  "Data Analysis",
  "Data Engineering",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "NLP",
  "Computer Vision",
  "Pandas",
  "NumPy",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "Excel",
  "Big Data",
  "ETL",
  "Data Warehousing",
  "Statistical Analysis",
  "R",
  "Cybersecurity",
  "Network Security",
  "Security Monitoring",
  "SIEM",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Incident Response",
  "Risk Assessment",
  "Compliance",
  "Firewall Configuration",
  "Cisco",
  "Routing",
  "Switching",
  "TCP/IP",
  "VPN",
  "DNS",
  "Networking",
  "Help Desk",
  "Hardware Troubleshooting",
  "Windows",
  "Windows Server",
  "Active Directory",
  "System Administration",
  "Virtualization",
  "Remote Desktop Support",
  "ITIL",
  "Product Management",
  "Product Strategy",
  "Project Management",
  "Program Management",
  "Project Coordination",
  "Agile",
  "Scrum",
  "Agile / Scrum",
  "Kanban",
  "Jira",
  "Stakeholder Management",
  "Requirements Analysis",
  "Requirements Gathering",
  "Documentation",
  "Roadmapping",
  "Risk Management",
  "Budget Management",
  "Sprint Planning",
  "Backlog Management",
  "OKRs",
  "KPI Tracking",
  "Business Analysis",
  "Process Improvement",
  "UI Design",
  "UX Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Prototyping",
  "Wireframing",
  "User Research",
  "Usability Testing",
  "Design Systems",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "InDesign",
  "Canva",
  "Branding",
  "Typography",
  "Graphic Design",
  "Premiere Pro",
  "After Effects",
  "Video Editing",
  "Storytelling",
  "Photography",
  "Videography",
  "CapCut",
  "SEO",
  "SEM",
  "Google Ads",
  "Google Analytics",
  "Keyword Research",
  "Content Marketing",
  "Content Writing",
  "Content Strategy",
  "Copywriting",
  "Email Marketing",
  "Social Media Management",
  "Meta Ads",
  "Brand Strategy",
  "WordPress",
  "Digital Marketing",
  "Marketing Automation",
  "Campaign Management",
  "Sales",
  "CRM",
  "Negotiation",
  "Cold Calling",
  "Lead Generation",
  "Account Management",
  "B2B Sales",
  "Field Sales",
  "Salesforce",
  "HubSpot",
  "Business Development",
  "Pipeline Management",
  "Sales Forecasting",
  "Closing Deals",
  "Customer Service",
  "Customer Support",
  "Technical Support",
  "Customer Retention",
  "Client Relations",
  "Communication",
  "Recruitment",
  "Talent Acquisition",
  "Interviewing",
  "Employee Relations",
  "HRIS",
  "Onboarding",
  "Performance Management",
  "Training and Development",
  "Compensation and Benefits",
  "Workforce Planning",
  "Accounting",
  "Bookkeeping",
  "Financial Reporting",
  "Financial Analysis",
  "Financial Modeling",
  "Taxation",
  "Tally",
  "VAT",
  "Reconciliation",
  "Budgeting",
  "Forecasting",
  "Auditing",
  "Accounts Payable",
  "Accounts Receivable",
  "QuickBooks",
  "SAP",
  "Operations Management",
  "Coordination",
  "Procurement",
  "Inventory Management",
  "Supply Chain Management",
  "Logistics",
  "Warehouse Management",
  "Vendor Management",
  "Quality Control",
  "Six Sigma",
  "Data Entry",
  "MS Office",
  "Microsoft Word",
  "PowerPoint",
  "Administration",
  "Office Administration",
  "Scheduling",
  "Filing",
  "Reporting",
  "Report Writing",
  "Research",
  "Attention to Detail",
  "AutoCAD",
  "Revit",
  "SolidWorks",
  "SketchUp",
  "Architectural Design",
  "Site Supervision",
  "Estimation",
  "Structural Analysis",
  "Structural Design",
  "Construction Management",
  "Electrical Design",
  "Circuit Design",
  "Mechanical Design",
  "CAD",
  "Building Codes",
  "Surveying",
  "HVAC",
  "Maintenance",
  "Written Communication",
  "Public Speaking",
  "Presentation Skills",
  "Leadership",
  "Team Management",
  "Critical Thinking",
  "Time Management",
  "Multitasking",
  "Adaptability",
  "Creativity",
  "Conflict Resolution",
  "Interpersonal Skills",
  "English",
  "Nepali",
  "Hindi",
];

export const skillsList = Array.from(new Set(rawSkills));

export function findSkills(query: string, limit = 8) {
  const normalizedQuery = query.trim().toLowerCase();
  if (!normalizedQuery) return skillsList.slice(0, limit);

  return skillsList
    .map((skill, index) => {
      const normalizedSkill = skill.toLowerCase();
      const words = normalizedSkill.split(/[^a-z0-9+#.]+/);
      const score = normalizedSkill.startsWith(normalizedQuery)
        ? 0
        : words.some((word) => word.startsWith(normalizedQuery))
          ? 1
          : normalizedSkill.includes(normalizedQuery)
            ? 2
            : 3;
      return { skill, index, score };
    })
    .filter(({ score }) => score < 3)
    .sort((a, b) => a.score - b.score || a.index - b.index)
    .slice(0, limit)
    .map(({ skill }) => skill);
}
